### ISSUE TITLE
When adding a new product, the next barcode is set to 3 instead of 2

### ISSUE THREAD

**Issue by kofi12** [Macintosh001/EECS-3311-final-project#23]

**Comment by kofi12** [comment]
I now see that we've hardcoded the next barcode to be 3 when testing the app

**Comment by kofi12** [comment]
made a new branch `iter1-barcode-fix` that reflects the changes made

**Comment by glassyeyedfish** [comment]
We want this hard coded because the `StubDatabase` should have products in it already. I think that would be better for the client team so they have an idea of what should be in the database at launch instead of an empty database.

With that being said, I think we should leave it hardcoded. In the future, the database will dynamically supply the `nextBarcode` to `Logic` in Iter2.

**Comment by kofi12** [comment]
Alright, makes sense
